version: '3'
services:
  app:
    user: $UID
    build:
      context: docker/app/
      dockerfile: Dockerfile
      args:
        UID: $UID
    container_name: template-app
    ports:
      - "8000:8000"
    tty: true
    volumes:
      - .:/var/www/app

  nginx:
    image: nginx:alpine
    container_name: template-nginx
    tty: true
    ports:
      - "80:80"
      - "443:443"
    links:
      - app
    depends_on:
      - app
    volumes:
      - .:/var/www/app
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
      - ./data/nginx/log:/var/log/nginx
